// AUTO-GENERATED by scripts/emit-mcp-wrappers.mjs — DO NOT EDIT.
// Regenerate: node scripts/extract-manifest.mjs && node scripts/emit-mcp-wrappers.mjs
// Source of truth: sbox-mcp-server/src/tools/ (zod schemas) → scripts/tools-manifest.json

using System.Text.Json.Nodes;
using System.Threading.Tasks;
using Editor.Mcp;

/// <summary>
/// Terrain sculpting, hills, trails and clearings; forest painting and POIs; cave paths; and
/// path-based object placement. Requires MapBuilder/ForestGenerator-style components in the project
/// (invoke_button works anywhere).
/// </summary>
[McpToolset( "bridge_world", "Terrain sculpting, hills, trails and clearings; forest painting and POIs; cave paths; and path-based object placement. Requires MapBuilder/ForestGenerator-style components in the project (invoke_button works anywhere)." )]
public static class BridgeWorldTools
{
	/// <summary>
	/// Append (or insert) a waypoint to CaveBuilder.Path. Z is depth (negative = underground).
	/// </summary>
	/// <param name="x"></param>
	/// <param name="y"></param>
	/// <param name="z">Z depth — negative = underground.</param>
	/// <param name="index">Optional insert position (default: append to end).</param>
	/// <param name="rebuild"></param>
	/// <param name="id"></param>
	/// <param name="component">Override the builder component type name — set this if your project's terrain/cave/forest component is named differently than the default (MapBuilder/CaveBuilder/ForestGenerator).</param>
	[McpTool( "add_cave_waypoint" )]
	public static Task<object> AddCaveWaypoint( double x, double y, double z = 0, int? index = null, bool rebuild = true, string id = null, string component = null )
		=> McpGate.Run( "add_cave_waypoint", McpGate.Args( ( "x", x ), ( "y", y ), ( "z", z ), ( "index", index ), ( "rebuild", rebuild ), ( "id", id ), ( "component", component ) ) );

	/// <summary>
	/// Add a point of interest (clearing) to ForestGenerator.POIs. Returns the index of the new POI for
	/// use with add_forest_trail.
	/// </summary>
	/// <param name="x"></param>
	/// <param name="y"></param>
	/// <param name="name"> Default: "POI".</param>
	/// <param name="radius"></param>
	/// <param name="density_multiplier">Multiplies forest density inside this POI's region.</param>
	/// <param name="rebuild">Forest gen is slow (~1s); default false to batch.</param>
	/// <param name="id"></param>
	/// <param name="component">Override the builder component type name — set this if your project's terrain/cave/forest component is named differently than the default (MapBuilder/CaveBuilder/ForestGenerator).</param>
	[McpTool( "add_forest_poi" )]
	public static Task<object> AddForestPoi( double x, double y, string name = "POI", double radius = 300, double density_multiplier = 1, bool rebuild = false, string id = null, string component = null )
		=> McpGate.Run( "add_forest_poi", McpGate.Args( ( "x", x ), ( "y", y ), ( "name", name ), ( "radius", radius ), ( "density_multiplier", density_multiplier ), ( "rebuild", rebuild ), ( "id", id ), ( "component", component ) ) );

	/// <summary>
	/// Add a trail gap between two POIs (by index) to ForestGenerator.Trails.
	/// </summary>
	/// <param name="from_index"></param>
	/// <param name="to_index"></param>
	/// <param name="rebuild"></param>
	/// <param name="id"></param>
	/// <param name="component">Override the builder component type name — set this if your project's terrain/cave/forest component is named differently than the default (MapBuilder/CaveBuilder/ForestGenerator).</param>
	[McpTool( "add_forest_trail" )]
	public static Task<object> AddForestTrail( int from_index, int to_index, bool rebuild = false, string id = null, string component = null )
		=> McpGate.Run( "add_forest_trail", McpGate.Args( ( "from_index", from_index ), ( "to_index", to_index ), ( "rebuild", rebuild ), ( "id", id ), ( "component", component ) ) );

	/// <summary>
	/// Add a flat clearing zone to MapBuilder (lerps height toward base inside radius).
	/// </summary>
	/// <param name="x"></param>
	/// <param name="y"></param>
	/// <param name="radius"></param>
	/// <param name="rebuild"></param>
	/// <param name="id"></param>
	/// <param name="component">Override the builder component type name — set this if your project's terrain/cave/forest component is named differently than the default (MapBuilder/CaveBuilder/ForestGenerator).</param>
	[McpTool( "add_terrain_clearing" )]
	public static Task<object> AddTerrainClearing( double x, double y, double radius = 300, bool rebuild = true, string id = null, string component = null )
		=> McpGate.Run( "add_terrain_clearing", McpGate.Args( ( "x", x ), ( "y", y ), ( "radius", radius ), ( "rebuild", rebuild ), ( "id", id ), ( "component", component ) ) );

	/// <summary>
	/// Add a hill (cosine-falloff bump) to MapBuilder. Negative height creates a depression.
	/// </summary>
	/// <param name="x">World X of hill center.</param>
	/// <param name="y">World Y of hill center.</param>
	/// <param name="radius">Hill radius in world units.</param>
	/// <param name="height">Peak height (negative for depression).</param>
	/// <param name="rebuild">Rebuild terrain after adding (set false to batch).</param>
	/// <param name="id"></param>
	/// <param name="component">Override the builder component type name — set this if your project's terrain/cave/forest component is named differently than the default (MapBuilder/CaveBuilder/ForestGenerator).</param>
	[McpTool( "add_terrain_hill" )]
	public static Task<object> AddTerrainHill( double x, double y, double radius = 500, double height = 100, bool rebuild = true, string id = null, string component = null )
		=> McpGate.Run( "add_terrain_hill", McpGate.Args( ( "x", x ), ( "y", y ), ( "radius", radius ), ( "height", height ), ( "rebuild", rebuild ), ( "id", id ), ( "component", component ) ) );

	/// <summary>
	/// Carve a trail depression between two points on MapBuilder.
	/// </summary>
	/// <param name="from"> JSON value.</param>
	/// <param name="to"> JSON value.</param>
	/// <param name="rebuild"></param>
	/// <param name="id"></param>
	/// <param name="component">Override the builder component type name — set this if your project's terrain/cave/forest component is named differently than the default (MapBuilder/CaveBuilder/ForestGenerator).</param>
	[McpTool( "add_terrain_trail" )]
	public static Task<object> AddTerrainTrail( JsonNode from, JsonNode to, bool rebuild = true, string id = null, string component = null )
		=> McpGate.Run( "add_terrain_trail", McpGate.Args( ( "from", from ), ( "to", to ), ( "rebuild", rebuild ), ( "id", id ), ( "component", component ) ) );

	/// <summary>
	/// Build a standalone heightmap terrain mesh from a hills/clearings JSON spec — independent of
	/// MapBuilder. Use when you don't have a MapBuilder component in the scene and want one-shot
	/// terrain.
	/// </summary>
	/// <param name="size">Total terrain size (world units, square).</param>
	/// <param name="resolution">Grid resolution per side.</param>
	/// <param name="name"> Default: "Generated Terrain".</param>
	/// <param name="hills"> JSON array. Default: [].</param>
	/// <param name="clearings"> JSON array. Default: [].</param>
	[McpTool( "build_terrain_mesh" )]
	public static Task<object> BuildTerrainMesh( double size = 9600, int resolution = 64, string name = "Generated Terrain", JsonNode hills = null, JsonNode clearings = null )
		=> McpGate.Run( "build_terrain_mesh", McpGate.Args( ( "size", size ), ( "resolution", resolution ), ( "name", name ), ( "hills", hills ), ( "clearings", clearings ) ) );

	/// <summary>
	/// Clear all waypoints in CaveBuilder and remove the cave from the scene.
	/// </summary>
	/// <param name="id"></param>
	/// <param name="component">Override the builder component type name — set this if your project's terrain/cave/forest component is named differently than the default (MapBuilder/CaveBuilder/ForestGenerator).</param>
	[McpTool( "clear_cave_path" )]
	public static Task<object> ClearCavePath( string id = null, string component = null )
		=> McpGate.Run( "clear_cave_path", McpGate.Args( ( "id", id ), ( "component", component ) ) );

	/// <summary>
	/// Wipe all POIs and trails in ForestGenerator and clear placed forest objects from the scene.
	/// </summary>
	/// <param name="id"></param>
	/// <param name="component">Override the builder component type name — set this if your project's terrain/cave/forest component is named differently than the default (MapBuilder/CaveBuilder/ForestGenerator).</param>
	[McpTool( "clear_forest_pois" )]
	public static Task<object> ClearForestPois( string id = null, string component = null )
		=> McpGate.Run( "clear_forest_pois", McpGate.Args( ( "id", id ), ( "component", component ) ) );

	/// <summary>
	/// Wipe Hills, Clearings, Trails, or all features from MapBuilder. 'what' is one of: Hills,
	/// Clearings, Trails, CavePath, all (default).
	/// </summary>
	/// <param name="what"> One of: Hills | Clearings | Trails | CavePath | all. Default: "all".</param>
	/// <param name="rebuild"></param>
	/// <param name="id"></param>
	/// <param name="component">Override the builder component type name — set this if your project's terrain/cave/forest component is named differently than the default (MapBuilder/CaveBuilder/ForestGenerator).</param>
	[McpTool( "clear_terrain_features" )]
	public static Task<object> ClearTerrainFeatures( string what = "all", bool rebuild = true, string id = null, string component = null )
		=> McpGate.Run( "clear_terrain_features", McpGate.Args( ( "what", what ), ( "rebuild", rebuild ), ( "id", id ), ( "component", component ) ) );

	/// <summary>
	/// Add a circular biome region with overridden forest density. Multiple regions stack via cosine
	/// falloff. density: 0=no trees, 1=normal, 2=double.
	/// </summary>
	/// <param name="x"></param>
	/// <param name="y"></param>
	/// <param name="radius"></param>
	/// <param name="density">Density multiplier (0=clear, 1=normal, 2=dense).</param>
	/// <param name="rebuild"></param>
	/// <param name="id"></param>
	/// <param name="component">Override the builder component type name — set this if your project's terrain/cave/forest component is named differently than the default (MapBuilder/CaveBuilder/ForestGenerator).</param>
	[McpTool( "paint_forest_density" )]
	public static Task<object> PaintForestDensity( double x, double y, double radius = 800, double density = 1, bool rebuild = false, string id = null, string component = null )
		=> McpGate.Run( "paint_forest_density", McpGate.Args( ( "x", x ), ( "y", y ), ( "radius", radius ), ( "density", density ), ( "rebuild", rebuild ), ( "id", id ), ( "component", component ) ) );

	/// <summary>
	/// Drop instances of a model along a path (list of points). Useful for fences, lampposts, road
	/// markers, lined-up rocks.
	/// </summary>
	/// <param name="model">Model path (e.g. 'models/dev/box.vmdl' or installed-asset path).</param>
	/// <param name="points">Path waypoints (at least 2). JSON array.</param>
	/// <param name="spacing">Distance between placements (world units).</param>
	/// <param name="jitter">Max random offset perpendicular to path.</param>
	/// <param name="min_scale"></param>
	/// <param name="max_scale"></param>
	/// <param name="seed"></param>
	/// <param name="name">Base name for placed objects. Default: "PathItem".</param>
	[McpTool( "place_along_path" )]
	public static Task<object> PlaceAlongPath( string model, JsonNode points, double spacing = 200, double jitter = 0, double min_scale = 1, double max_scale = 1, int seed = 42, string name = "PathItem" )
		=> McpGate.Run( "place_along_path", McpGate.Args( ( "model", model ), ( "points", points ), ( "spacing", spacing ), ( "jitter", jitter ), ( "min_scale", min_scale ), ( "max_scale", max_scale ), ( "seed", seed ), ( "name", name ) ) );

	/// <summary>
	/// Sample MapBuilder terrain height at world (x, y). Returns z (the surface height). Use to place
	/// props on the terrain surface.
	/// </summary>
	/// <param name="x">World X coordinate.</param>
	/// <param name="y">World Y coordinate.</param>
	/// <param name="id">Optional GameObject GUID for MapBuilder.</param>
	/// <param name="component">Override the terrain component type name (default MapBuilder).</param>
	[McpTool.ReadOnly( "raycast_terrain" )]
	public static Task<object> RaycastTerrain( double x, double y, string id = null, string component = null )
		=> McpGate.Run( "raycast_terrain", McpGate.Args( ( "x", x ), ( "y", y ), ( "id", id ), ( "component", component ) ) );

	/// <summary>
	/// Apply a heightmap brush at (x, y) to MapBuilder. Modes: raise, lower, flatten, smooth. Modifies
	/// the current heightmap directly and rebuilds the mesh; survives between calls until you press
	/// Build Terrain again.
	/// </summary>
	/// <param name="x">World X of brush center.</param>
	/// <param name="y">World Y of brush center.</param>
	/// <param name="radius">Brush radius in world units.</param>
	/// <param name="strength">Height delta (units) for raise/lower; ignored for flatten/smooth.</param>
	/// <param name="mode"> One of: raise | lower | flatten | smooth. Default: "raise".</param>
	/// <param name="id"></param>
	/// <param name="component">Override the builder component type name — set this if your project's terrain/cave/forest component is named differently than the default (MapBuilder/CaveBuilder/ForestGenerator).</param>
	[McpTool( "sculpt_terrain" )]
	public static Task<object> SculptTerrain( double x, double y, double radius = 400, double strength = 50, string mode = "raise", string id = null, string component = null )
		=> McpGate.Run( "sculpt_terrain", McpGate.Args( ( "x", x ), ( "y", y ), ( "radius", radius ), ( "strength", strength ), ( "mode", mode ), ( "id", id ), ( "component", component ) ) );

	/// <summary>
	/// Set ForestGenerator.Seed and regenerate. Useful for re-rolling layouts.
	/// </summary>
	/// <param name="seed"></param>
	/// <param name="rebuild"></param>
	/// <param name="id"></param>
	/// <param name="component">Override the builder component type name — set this if your project's terrain/cave/forest component is named differently than the default (MapBuilder/CaveBuilder/ForestGenerator).</param>
	[McpTool( "set_forest_seed" )]
	public static Task<object> SetForestSeed( int seed = 77, bool rebuild = true, string id = null, string component = null )
		=> McpGate.Run( "set_forest_seed", McpGate.Args( ( "seed", seed ), ( "rebuild", rebuild ), ( "id", id ), ( "component", component ) ) );
}
