// AUTO-GENERATED by scripts/emit-mcp-wrappers.mjs — DO NOT EDIT.
// Regenerate: node scripts/extract-manifest.mjs && node scripts/emit-mcp-wrappers.mjs
// Source of truth: sbox-mcp-server/src/tools/ (zod schemas) → scripts/tools-manifest.json

using System.Text.Json.Nodes;
using System.Threading.Tasks;
using Editor.Mcp;

/// <summary>
/// List sounds, author .sound events, attach sound components, and preview audio in the editor.
/// </summary>
[McpToolset( "bridge_audio", "List sounds, author .sound events, attach sound components, and preview audio in the editor." )]
public static class BridgeAudioTools
{
	/// <summary>
	/// Attach a sound event to a GameObject via SoundPointComponent. Creates the component if needed.
	/// </summary>
	/// <param name="id">GUID of the GameObject.</param>
	/// <param name="sound">Sound event path (e.g. 'sounds/ambient_wind.sound').</param>
	/// <param name="playOnStart">Whether the sound plays automatically when the game starts.</param>
	[McpTool( "assign_sound" )]
	public static Task<object> AssignSound( string id, string sound, bool? playOnStart = null )
		=> McpGate.Run( "assign_sound", McpGate.Args( ( "id", id ), ( "sound", sound ), ( "playOnStart", playOnStart ) ) );

	/// <summary>
	/// Create a new sound event file (.sound) with volume, pitch, distance falloff, and looping
	/// settings.
	/// </summary>
	/// <param name="path">Path for the sound event file (e.g. 'sounds/footstep.sound').</param>
	/// <param name="sound">Path to the source sound asset (.vsnd).</param>
	/// <param name="volume">Volume multiplier (0-1). Defaults to 1.0.</param>
	/// <param name="pitch">Pitch multiplier. Defaults to 1.0.</param>
	/// <param name="minDistance">Minimum distance before falloff starts (units). Defaults to 100.</param>
	/// <param name="maxDistance">Maximum audible distance (units). Defaults to 2000.</param>
	/// <param name="loop">Whether the sound should loop. Defaults to false.</param>
	[McpTool( "create_sound_event" )]
	public static Task<object> CreateSoundEvent( string path, string sound, double? volume = null, double? pitch = null, double? minDistance = null, double? maxDistance = null, bool? loop = null )
		=> McpGate.Run( "create_sound_event", McpGate.Args( ( "path", path ), ( "sound", sound ), ( "volume", volume ), ( "pitch", pitch ), ( "minDistance", minDistance ), ( "maxDistance", maxDistance ), ( "loop", loop ) ) );

	/// <summary>
	/// List available sound assets in the project and installed packages. Filter by name.
	/// </summary>
	/// <param name="filter">Search filter for sound name or path.</param>
	/// <param name="maxResults">Maximum results. Defaults to 50.</param>
	[McpTool.ReadOnly( "list_sounds" )]
	public static Task<object> ListSounds( string filter = null, double? maxResults = null )
		=> McpGate.Run( "list_sounds", McpGate.Args( ( "filter", filter ), ( "maxResults", maxResults ) ) );

	/// <summary>
	/// Play a sound in the editor for testing without entering play mode.
	/// </summary>
	/// <param name="sound">Sound event or asset path to preview.</param>
	/// <param name="volume">Preview volume (0-1). Defaults to 1.0.</param>
	[McpTool( "play_sound_preview" )]
	public static Task<object> PlaySoundPreview( string sound, double? volume = null )
		=> McpGate.Run( "play_sound_preview", McpGate.Args( ( "sound", sound ), ( "volume", volume ) ) );
}
