// AUTO-GENERATED by scripts/emit-mcp-wrappers.mjs — DO NOT EDIT.
// Regenerate: node scripts/extract-manifest.mjs && node scripts/emit-mcp-wrappers.mjs
// Source of truth: sbox-mcp-server/src/tools/ (zod schemas) → scripts/tools-manifest.json

using System.Text.Json.Nodes;
using System.Threading.Tasks;
using Editor.Mcp;

/// <summary>
/// Create prefabs from scene objects, instantiate them, list and inspect them, and wire prefab
/// references into component properties.
/// </summary>
[McpToolset( "bridge_prefab", "Create prefabs from scene objects, instantiate them, list and inspect them, and wire prefab references into component properties." )]
public static class BridgePrefabTools
{
	/// <summary>
	/// Save an existing GameObject as a .prefab file. NOTE: this writes a minimal descriptor (name,
	/// enabled flag, component TYPE names) — component property values and children are NOT serialized,
	/// so it is a lightweight template rather than a full s&amp;box prefab asset. Returns { created,
	/// path, sourceId } — pass path to instantiate_prefab or get_prefab_info.
	/// </summary>
	/// <param name="id">GUID of the GameObject to save as prefab.</param>
	/// <param name="path">Path for the prefab file relative to project root (e.g. 'prefabs/enemies/grunt.prefab').</param>
	[McpTool( "create_prefab" )]
	public static Task<object> CreatePrefab( string id, string path )
		=> McpGate.Run( "create_prefab", McpGate.Args( ( "id", id ), ( "path", path ) ) );

	/// <summary>
	/// Get detailed information about a prefab file. Returns { path, name, size, modified, content } —
	/// content is the prefab's full raw JSON, so use this to inspect what a prefab actually contains
	/// before instantiate_prefab (find prefabs with list_prefabs).
	/// </summary>
	/// <param name="path">Path to the .prefab file (e.g. 'prefabs/enemies/grunt.prefab').</param>
	[McpTool.ReadOnly( "get_prefab_info" )]
	public static Task<object> GetPrefabInfo( string path )
		=> McpGate.Run( "get_prefab_info", McpGate.Args( ( "path", path ) ) );

	/// <summary>
	/// Spawn a prefab instance into the active scene at an optional position and rotation. NOTE: basic
	/// instantiation — it creates a new GameObject named after the prefab; components are NOT recreated
	/// from the file (the full s&amp;box prefab pipeline isn't wired), so re-add them with
	/// add_component_with_properties. Returns { instantiated, prefab, gameObject, note } —
	/// gameObject.id is the new GUID for follow-up calls.
	/// </summary>
	/// <param name="path">Path to the .prefab file (e.g. 'prefabs/enemies/grunt.prefab').</param>
	/// <param name="position">World position to spawn at — object {x,y,z} or comma string "x,y,z". Defaults to origin. As "x,y,z" (or JSON {x,y,z}).</param>
	/// <param name="rotation">Rotation as euler angles. Defaults to identity. As "pitch,yaw,roll" degrees.</param>
	/// <param name="scale">Uniform scale multiplier. Defaults to 1.0.</param>
	/// <param name="parent">GUID of parent GameObject to attach to.</param>
	[McpTool( "instantiate_prefab" )]
	public static Task<object> InstantiatePrefab( string path, string position = null, string rotation = null, double? scale = null, string parent = null )
		=> McpGate.Run( "instantiate_prefab", McpGate.Args( ( "path", path ), ( "position", position ), ( "rotation", rotation ), ( "scale", scale ), ( "parent", parent ) ) );

	/// <summary>
	/// List all .prefab files in the project. Filter by name or path.
	/// </summary>
	/// <param name="filter">Search filter for prefab name or path.</param>
	/// <param name="maxResults">Maximum results to return. Defaults to 100.</param>
	[McpTool.ReadOnly( "list_prefabs" )]
	public static Task<object> ListPrefabs( string filter = null, double? maxResults = null )
		=> McpGate.Run( "list_prefabs", McpGate.Args( ( "filter", filter ), ( "maxResults", maxResults ) ) );

	/// <summary>
	/// Set a GameObject-typed property on a component to a loaded prefab. Use this when set_property
	/// can't handle prefab references (which it can't, because prefabs are GameObjects not primitives).
	/// </summary>
	/// <param name="id">GUID of the GameObject holding the component.</param>
	/// <param name="component">Component type name.</param>
	/// <param name="property">Property name to set (must be GameObject-typed).</param>
	/// <param name="prefabPath">Prefab asset path (e.g. 'prefabs/player.prefab').</param>
	[McpTool( "set_prefab_ref" )]
	public static Task<object> SetPrefabRef( string id, string component, string property, string prefabPath )
		=> McpGate.Run( "set_prefab_ref", McpGate.Args( ( "id", id ), ( "component", component ), ( "property", property ), ( "prefabPath", prefabPath ) ) );
}
