// AUTO-GENERATED by scripts/emit-mcp-wrappers.mjs — DO NOT EDIT.
// Regenerate: node scripts/extract-manifest.mjs && node scripts/emit-mcp-wrappers.mjs
// Source of truth: sbox-mcp-server/src/tools/ (zod schemas) → scripts/tools-manifest.json

using System.Text.Json.Nodes;
using System.Threading.Tasks;
using Editor.Mcp;

/// <summary>
/// Bulk operations across many GameObjects in one call, with dry-run validation before applying.
/// Get target ids from find_objects or get_selected_objects.
/// </summary>
[McpToolset( "bridge_batch", "Bulk operations across many GameObjects in one call, with dry-run validation before applying. Get target ids from find_objects or get_selected_objects." )]
public static class BridgeBatchTools
{
	/// <summary>
	/// Set ONE component property to the same value across MANY GameObjects in a single call (e.g. Tint
	/// on 40 props, Enabled on every light). Pass dryRun:true first to validate — it reports each
	/// object's current value and what would change WITHOUT applying anything. Returns { total,
	/// succeeded, failed, dryRun, results } with per-object ok/error and the previous value on success.
	/// Get ids from find_objects or get_selected_objects. Scene-mutating: refused during play mode.
	/// Value coercion matches set_property (numbers, bools, enums, 'x,y,z' vectors, colors, asset
	/// paths).
	/// </summary>
	/// <param name="ids">GUIDs of the GameObjects to modify (from find_objects, get_scene_hierarchy, or get_selected_objects).</param>
	/// <param name="component">Component type name present on each object, e.g. 'ModelRenderer', 'PointLight'.</param>
	/// <param name="property">Property name to set, e.g. 'Tint', 'Enabled', 'LightColor' (see get_all_properties).</param>
	/// <param name="value">New value — number, bool, string, enum name, 'x,y,z' vector, color, or asset path. JSON value.</param>
	/// <param name="dryRun">true = validate and report current values without changing anything. Default false.</param>
	[McpTool( "batch_set_property" )]
	public static Task<object> BatchSetProperty( string[] ids, string component, string property, JsonNode value, bool? dryRun = null )
		=> McpGate.Run( "batch_set_property", McpGate.Args( ( "ids", ids ), ( "component", component ), ( "property", property ), ( "value", value ), ( "dryRun", dryRun ) ) );
}
