// AUTO-GENERATED by scripts/emit-mcp-wrappers.mjs — DO NOT EDIT.
// Regenerate: node scripts/extract-manifest.mjs && node scripts/emit-mcp-wrappers.mjs
// Source of truth: sbox-mcp-server/src/tools/ (zod schemas) → scripts/tools-manifest.json

using System.Text.Json.Nodes;
using System.Threading.Tasks;
using Editor.Mcp;

/// <summary>
/// Lint and validate the project: networking footguns, sandbox whitelist violations, Razor
/// transpiler footguns, scene setup issues, publishing readiness, save-file inspection, and
/// networked-object state dumps.
/// </summary>
[McpToolset( "bridge_validation", "Lint and validate the project: networking footguns, sandbox whitelist violations, Razor transpiler footguns, scene setup issues, publishing readiness, save-file inspection, and networked-object state dumps." )]
public static class BridgeValidationTools
{
	/// <summary>
	/// Inspect the live networking contract of a GameObject: Network.Owner/IsProxy/IsOwner/Active,
	/// OwnerTransfer + OrphanedMode, and every component's [Sync] property names, SyncFlags, and
	/// current values (host vs proxy). Unlike get_network_status (session-only), this is per-object —
	/// the way to verify a host-authoritative or ownership change actually replicated. Works in edit or
	/// play mode.
	/// </summary>
	/// <param name="id">GUID of the GameObject to inspect.</param>
	/// <param name="allProps">Include all component properties, not just [Sync]-marked ones.</param>
	[McpTool.ReadOnly( "inspect_networked_object" )]
	public static Task<object> InspectNetworkedObject( string id, bool allProps = false )
		=> McpGate.Run( "inspect_networked_object", McpGate.Args( ( "id", id ), ( "allProps", allProps ) ) );

	/// <summary>
	/// Static-scan the project's C# for the highest-frequency networking/authority bugs: a mutator that
	/// writes a [Sync] field with no IsProxy/Networking.IsHost guard; money/health/score-shaped fields
	/// marked plain [Sync] (should be SyncFlags.FromHost); List&lt;&gt;/Dictionary&lt;&gt; marked
	/// [Sync] (should be NetList/NetDictionary); [Sync] fields typed Connection/GameObject (sync a Guid
	/// instead); [Rpc.Host] methods that mutate without re-checking Rpc.Caller; and component swaps /
	/// reflection writes missing Network.Refresh(). Returns findings with file:line + the suggested
	/// fix.
	/// </summary>
	/// <param name="path">Optional sub-path under the project (e.g. 'Code/Player') to scope the scan; omit for the whole project.</param>
	[McpTool.ReadOnly( "networking_lint" )]
	public static Task<object> NetworkingLint( string path = null )
		=> McpGate.Run( "networking_lint", McpGate.Args( ( "path", path ) ) );

	/// <summary>
	/// Static-scan .razor and .razor.scss files for the silent footguns that crash the Razor transpiler
	/// or stylesheet engine with no useful error message: switch expressions inside @code blocks (use
	/// if/else instead), non-ASCII/emoji inside @code (move to markup or a string constant),
	/// PanelComponent subclasses missing a BuildHash override (panel never re-renders), and root
	/// uppercase type-selector rules in .razor.scss (silently skipped -- use a class selector like
	/// .my-panel). Returns { scanned, findings: [{file, line, match, advice}], clean } matching the
	/// sandbox_lint shape.
	/// </summary>
	/// <param name="directory">Subdirectory under the project root to scan (e.g. 'UI', 'Code'). Defaults to 'Code'.</param>
	[McpTool.ReadOnly( "razor_lint" )]
	public static Task<object> RazorLint( string directory = null )
		=> McpGate.Run( "razor_lint", McpGate.Args( ( "directory", directory ) ) );

	/// <summary>
	/// Static-scan the project's C# for s&amp;box sandbox whitelist violations BEFORE they cause
	/// compile errors: System.MathF (use MathX), System.Math (use MathX), Array.Clone() (use
	/// .ToArray()), System.Net / raw sockets (use Sandbox.Http), System.IO.File (use FileSystem.Data),
	/// and raw System.Threading.Thread (use async/Task or GameTask). Returns { scanned, findings:
	/// [{file, line, match, advice}], clean }. Scope to a subdirectory with the directory param.
	/// </summary>
	/// <param name="directory">Subdirectory under the project root to scan (e.g. 'Code', 'Code/Player'). Defaults to 'Code'.</param>
	[McpTool.ReadOnly( "sandbox_lint" )]
	public static Task<object> SandboxLint( string directory = null )
		=> McpGate.Run( "sandbox_lint", McpGate.Args( ( "directory", directory ) ) );

	/// <summary>
	/// Inspect the game's FileSystem.Data save files — the assistant is otherwise blind to persisted
	/// state. action='list' enumerates files under a folder (with size/mtime); action='read' dumps a
	/// save file's JSON; action='diff' compares two save files key-by-key. Use to verify a save
	/// actually wrote, debug a load/migration, or confirm a sanitize/clamp ran.
	/// </summary>
	/// <param name="action"> One of: list | read | diff. Default: "list".</param>
	/// <param name="path">File or folder path under FileSystem.Data (e.g. 'lumber_corp2_progress' or '&lt;folder&gt;/steam_123.json').</param>
	/// <param name="pathB">Second file path for action='diff'.</param>
	[McpTool.ReadOnly( "save_inspect" )]
	public static Task<object> SaveInspect( string action = "list", string path = null, string pathB = null )
		=> McpGate.Run( "save_inspect", McpGate.Args( ( "action", action ), ( "path", path ), ( "pathB", pathB ) ) );

	/// <summary>
	/// Validate the active scene for the silent setup footguns that break controllers/physics/cameras:
	/// no CameraComponent, no player controller, multiple root Rigidbodies, a Rigidbody with
	/// MotionEnabled=false fighting a kinematic root, IsTrigger colliders that Scene.Trace will ignore,
	/// child Rigidbodies breaking collider binding, and missing required child anchors. Returns each
	/// issue with the GameObject and the exact fix.
	/// </summary>
	[McpTool.ReadOnly( "scene_validate" )]
	public static Task<object> SceneValidate()
		=> McpGate.Run( "scene_validate", McpGate.Args() );

	/// <summary>
	/// Read from Sandbox.Services — the cloud stats/leaderboard layer many games use as their real DB.
	/// action='stats' lists/reads the project's stat definitions and the local player's values;
	/// action='leaderboard' fetches a leaderboard board's top entries. Read-only. Use to verify a
	/// Stats.Increment/SetValue path or a leaderboard wired correctly.
	/// </summary>
	/// <param name="action"> One of: stats | leaderboard. Default: "stats".</param>
	/// <param name="name">Stat name (action='stats') or leaderboard/board name (action='leaderboard').</param>
	/// <param name="limit">Max leaderboard entries to return.</param>
	[McpTool.ReadOnly( "services_query" )]
	public static Task<object> ServicesQuery( string action = "stats", string name = null, int limit = 10 )
		=> McpGate.Run( "services_query", McpGate.Args( ( "action", action ), ( "name", name ), ( "limit", limit ) ) );

	/// <summary>
	/// Validate that the project is ready for publishing. Checks: compile errors, metadata
	/// completeness, scenes, scripts, thumbnail, and project type.
	/// </summary>
	[McpTool.ReadOnly( "validate_project" )]
	public static Task<object> ValidateProject()
		=> McpGate.Run( "validate_project", McpGate.Args() );
}
