import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { BridgeClient } from "../transport/bridge-client.js";

/**
 * World & Render family — three tools:
 *
 *   - add_water_body            WaterVolume physics volume + trigger BoxCollider
 *                               footprint + optional tinted visual surface
 *   - add_render_target_camera  secondary camera → render-target texture →
 *                               display surface (CCTV / mirror / portal)
 *   - add_daynight_sun          codegen sun/sky driver bound to the component
 *                               generated by create_day_night_clock
 *
 * add_water_body is scene-direct; the other two generate a sealed game-code
 * component (hotload to compile). All three are scene/file-mutating and are
 * refused during play mode by the bridge dispatch.
 */

// Colour / vector accepted as EITHER an object OR a comma string, passed
// through unchanged. The C# handler parses both forms (source of truth). See
// the cross-language vector/color contract.
const ColorObject = z.object({
  r: z.number().min(0).describe("Red, 0-1"),
  g: z.number().min(0).describe("Green, 0-1"),
  b: z.number().min(0).describe("Blue, 0-1"),
  a: z.number().min(0).max(1).optional().describe("Alpha, 0-1 (default 1)"),
});

const ColorSchema = z
  .union([
    ColorObject,
    z.string().describe('Comma string "r,g,b,a", e.g. "1,0,0,1"'),
  ])
  .describe('RGBA colour — object {r,g,b,a} (0-1) OR comma string "r,g,b,a"');

const Vector3Object = z.object({ x: z.number(), y: z.number(), z: z.number() });

const Vector3Schema = z
  .union([
    Vector3Object,
    z.string().describe('Comma string "x,y,z", e.g. "0,0,200"'),
  ])
  .describe('World position — object {x,y,z} OR comma string "x,y,z"');

const RotationSchema = z
  .object({ pitch: z.number(), yaw: z.number(), roll: z.number() })
  .describe("Rotation {pitch,yaw,roll} in degrees");

export function registerWorldRenderTools(
  server: McpServer,
  bridge: BridgeClient
): void {
  // ── add_water_body ───────────────────────────────────────────────
  server.tool(
    "add_water_body",
    "Create a swimmable/buoyant water region: a GameObject with a WaterVolume (s&box's buoyancy + drag physics volume, region defined by a trigger BoxCollider sized to `size`) plus, by default, a simple flat translucent-blue surface box at the water line so it's visible. HONEST LIMIT: the visual is a tinted dev-box stand-in, NOT a Gerstner/water shader — the dev material may render the tint opaque; swap in a real water material later. Only the WaterVolume properties you pass are set (engine defaults otherwise). Returns {created, gameObject{id,...}, size, appliedProperties[], surface{id,...}|null, note, nextSteps[]}. Next: start_play and drop a physics prop in to verify buoyancy; tune FluidDensity/LinearDrag/WaveAmplitude etc. with set_property on the WaterVolume. Scene-mutating — refused during play mode.",
    {
      name: z
        .string()
        .optional()
        .describe("GameObject name. Defaults to 'Water'"),
      position: Vector3Schema.optional().describe(
        "World position of the volume's CENTRE (the surface sits at z + size.z/2 + surfaceOffset)"
      ),
      size: z
        .string()
        .optional()
        .describe(
          "Full extents of the volume as 'x,y,z' world units. Defaults to '512,512,128'"
        ),
      density: z
        .number()
        .optional()
        .describe(
          "WaterVolume.FluidDensity — higher = more buoyant. Engine default when omitted"
        ),
      linearDrag: z
        .number()
        .optional()
        .describe("WaterVolume.LinearDrag on submerged bodies. Engine default when omitted"),
      angularDrag: z
        .number()
        .optional()
        .describe("WaterVolume.AngularDrag on submerged bodies. Engine default when omitted"),
      waveAmplitude: z
        .number()
        .optional()
        .describe("WaterVolume.WaveAmplitude — physics wave height (does NOT animate the visual surface)"),
      waveFrequency: z
        .number()
        .optional()
        .describe("WaterVolume.WaveFrequency — physics wave frequency"),
      fluidVelocity: Vector3Schema.optional().describe(
        "WaterVolume.FluidVelocity — current/flow direction and speed, world units/s"
      ),
      surfaceOffset: z
        .number()
        .optional()
        .describe("WaterVolume.SurfaceOffset — shifts the water line relative to the top of the box"),
      visualSurface: z
        .boolean()
        .optional()
        .describe("Create the tinted surface box child. Defaults to true"),
      surfaceColor: ColorSchema.optional().describe(
        "Tint of the visual surface. Defaults to translucent blue (0.15,0.35,0.55,0.6)"
      ),
      parentId: z.string().optional().describe("GUID of a parent GameObject"),
    },
    async (params) => {
      const res = await bridge.send("add_water_body", params);
      if (!res.success) {
        return { content: [{ type: "text", text: `Error: ${res.error}` }] };
      }
      return { content: [{ type: "text", text: JSON.stringify(res.data, null, 2) }] };
    }
  );

  // ── add_render_target_camera ─────────────────────────────────────
  server.tool(
    "add_render_target_camera",
    "CCTV / security monitor / mirror / simple portal: creates a secondary camera (IsMainCamera=false, Priority param) positioned/rotated or aimed at a target object, a display surface (scaled box with a ModelRenderer), and GENERATES a sealed wiring component that at runtime creates the render-target Texture (Texture.CreateRenderTarget builder), assigns camera.RenderTarget and sets the texture onto an anonymous complex-shader material on the display (attribute 'Color' = albedo; the screen is scene-lit, not emissive/unlit). Returns {created, camera{id,...}, display{id,...}|null, className, path, generatedCode, attachedAndWired, resolution, nextSteps[]}. FIRST call generates the .cs → follow nextSteps: trigger_hotload, then add_component_with_properties on the display with properties {SourceCamera: <camera GUID>}; a REPEAT call reusing the same `name` after the hotload attaches AND wires everything automatically (attachedAndWired=true). The feed only renders in play mode — verify with start_play + capture_view. If `name`'s .cs file exists but isn't compiled yet, the call errors — hotload first. Scene/file-mutating — refused during play mode.",
    {
      name: z
        .string()
        .optional()
        .describe(
          "Class name for the generated wiring component. Defaults to 'RenderTargetDisplay'. Reuse the same name for extra cameras — after a hotload the class is reused and wired in one shot"
        ),
      directory: z
        .string()
        .optional()
        .describe("Subdirectory for the generated .cs file. Defaults to 'Code'"),
      cameraName: z
        .string()
        .optional()
        .describe("GameObject name for the camera. Defaults to 'RT Camera'"),
      position: Vector3Schema.optional().describe("World position of the camera"),
      rotation: RotationSchema.optional().describe("World rotation of the camera"),
      lookAtId: z
        .string()
        .optional()
        .describe(
          "GUID of a GameObject to aim the camera at (overrides rotation; from get_scene_hierarchy / find_objects)"
        ),
      priority: z
        .number()
        .optional()
        .describe("CameraComponent.Priority (integer). Defaults to 1"),
      fieldOfView: z
        .number()
        .optional()
        .describe("Camera field of view in degrees (clamped 5-170). Engine default when omitted"),
      resolution: z
        .string()
        .optional()
        .describe("Render-target size as 'width,height' pixels (min 16). Defaults to '512,512'"),
      backgroundColor: ColorSchema.optional().describe(
        "Camera background colour. Engine default when omitted"
      ),
      createDisplay: z
        .boolean()
        .optional()
        .describe(
          "Create the display surface GameObject. Defaults to true. Pass false to wire your own surface later"
        ),
      displayPosition: Vector3Schema.optional().describe(
        "World position of the display surface"
      ),
      displayRotation: RotationSchema.optional().describe(
        "World rotation of the display surface"
      ),
      displaySize: z
        .string()
        .optional()
        .describe(
          "Display box extents as 'x,y,z' world units (thin x = a wall screen facing ±x). Defaults to '4,128,72'"
        ),
      attribute: z
        .string()
        .optional()
        .describe(
          "Material attribute that receives the texture. Defaults to 'Color' (albedo on the complex shader). Sanitized to [A-Za-z0-9_]"
        ),
    },
    async (params) => {
      const res = await bridge.send("add_render_target_camera", params);
      if (!res.success) {
        return { content: [{ type: "text", text: `Error: ${res.error}` }] };
      }
      return { content: [{ type: "text", text: JSON.stringify(res.data, null, 2) }] };
    }
  );

  // ── add_daynight_sun ─────────────────────────────────────────────
  server.tool(
    "add_daynight_sun",
    "Generate a sun/sky driver component for the clock made by create_day_night_clock — a COMPANION, not a replacement: the clock owns TimeOfDay, this renders it. Every frame it reads TimeOfDay/SunriseHour/SunsetHour off the clock (sibling first, else first in scene, retrying 1/s) and drives a DirectionalLight: sunrise→sunset maps to a 0-180° pitch arc (continuing below the horizon at night), LightColor runs a hardcoded gradient (warm dawn → white noon → orange dusk → dim blue night, HDR-scaled by Intensity since s&box lights have no Brightness field), and optionally lerps the SkyBox2D Tint between night blue and day white. The clock CLASS NAME is baked in as a typed reference — the call ERRORS if `clockClass` isn't found in the TypeLibrary or any project .cs (run create_day_night_clock first; a bad token would break the whole game-assembly compile). Returns {created, path, className, clockClass, sunYaw, intensity, driveSkybox, placedOn, note, nextSteps[]}. Next: trigger_hotload → attach to the DirectionalLight's GameObject → start_play, set_runtime_property TimeOfDay on the clock (6/12/20/0) + capture_view to verify the looks. File/scene-mutating — refused during play mode.",
    {
      name: z
        .string()
        .optional()
        .describe("Class name for the generated component. Defaults to 'DayNightSun'"),
      directory: z
        .string()
        .optional()
        .describe("Subdirectory for the generated .cs file. Defaults to 'Code'"),
      clockClass: z
        .string()
        .optional()
        .describe(
          "Class name of the day-night clock to bind to (the `name` you gave create_day_night_clock). Defaults to 'DayNightClock'. Must already exist as a compiled type or a project .cs file"
        ),
      sunYaw: z
        .number()
        .optional()
        .describe("Compass heading of the sun's arc in degrees. Defaults to 30"),
      intensity: z
        .number()
        .optional()
        .describe(
          "Brightness multiplier on the colour gradient (HDR, >1 valid; intensity = colour magnitude). Defaults to 1"
        ),
      driveSkybox: z
        .boolean()
        .optional()
        .describe("Also tint the scene's SkyBox2D between night blue and day white. Defaults to true"),
      targetId: z
        .string()
        .optional()
        .describe(
          "GUID of a GameObject to attach to (only attaches if the type is already loaded — hotload first)"
        ),
    },
    async (params) => {
      const res = await bridge.send("add_daynight_sun", params);
      if (!res.success) {
        return { content: [{ type: "text", text: `Error: ${res.error}` }] };
      }
      return { content: [{ type: "text", text: JSON.stringify(res.data, null, 2) }] };
    }
  );
}
